import { createRequire } from "module";
import path from "path";

const require = createRequire(path.join(process.cwd(), "package.json"));
const PDFDocument = require("pdfkit") as typeof import("pdfkit");

interface AuditPdfData {
  url: string;
  title: string | null;
  geoScore: number | null;
  aiReadinessScore: number | null;
  citationScore: number | null;
  authorityScore: number | null;
  entityScore: number | null;
  eeatScore: number | null;
  contentStructureScore: number | null;
  internalLinkScore: number | null;
  readabilityScore: number | null;
  faqScore: number | null;
  summary: string | null;
  recommendations: { category: string; priority: string; title: string; description: string }[];
  entities: { name: string; type: string; count: number }[];
  crawlData?: { pagesCrawled: number; orphanPages: string[] } | null;
}

export function generateAuditPdf(data: AuditPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(22).fillColor("#6d28d9").text("GeoPilot — GEO Audit Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#666").text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
    doc.moveDown(1);

    doc.fontSize(14).fillColor("#000").text(data.title || data.url);
    doc.fontSize(10).fillColor("#444").text(data.url);
    doc.moveDown(1);

    // Scores
    doc.fontSize(16).fillColor("#6d28d9").text("Scores");
    doc.moveDown(0.5);

    const scores = [
      ["GEO Score", data.geoScore],
      ["AI Readiness", data.aiReadinessScore],
      ["E-E-A-T", data.eeatScore],
      ["Authority", data.authorityScore],
      ["Entity Coverage", data.entityScore],
      ["Citation", data.citationScore],
      ["Content Structure", data.contentStructureScore],
      ["Internal Links", data.internalLinkScore],
      ["Readability", data.readabilityScore],
      ["FAQ Score", data.faqScore],
    ];

    doc.fontSize(10).fillColor("#000");
    scores.forEach(([label, score]) => {
      doc.text(`${label}: ${score ?? "N/A"}/100`);
    });
    doc.moveDown(1);

    if (data.crawlData) {
      doc.fontSize(14).fillColor("#6d28d9").text("Site Crawl");
      doc.fontSize(10).fillColor("#000");
      doc.text(`Pages crawled: ${data.crawlData.pagesCrawled}`);
      if (data.crawlData.orphanPages.length > 0) {
        doc.text(`Orphan pages: ${data.crawlData.orphanPages.length}`);
        data.crawlData.orphanPages.slice(0, 5).forEach((p) => doc.text(`  • ${p}`));
      }
      doc.moveDown(1);
    }

    if (data.summary) {
      doc.fontSize(14).fillColor("#6d28d9").text("Summary");
      doc.fontSize(10).fillColor("#000").text(data.summary, { width: 500 });
      doc.moveDown(1);
    }

    if (data.recommendations.length > 0) {
      doc.fontSize(14).fillColor("#6d28d9").text("Recommendations");
      doc.moveDown(0.5);
      data.recommendations.slice(0, 15).forEach((rec, i) => {
        doc.fontSize(10).fillColor("#000").text(`${i + 1}. [${rec.priority.toUpperCase()}] ${rec.title}`);
        doc.fontSize(9).fillColor("#555").text(rec.description, { width: 480 });
        doc.moveDown(0.3);
      });
      doc.moveDown(0.5);
    }

    if (data.entities.length > 0) {
      doc.fontSize(14).fillColor("#6d28d9").text("Top Entities");
      doc.fontSize(10).fillColor("#000");
      data.entities.slice(0, 15).forEach((e) => {
        doc.text(`• ${e.name} (${e.type}) — ${e.count} mentions`);
      });
    }

    doc.fontSize(8).fillColor("#999").text(
      "Generated by GeoPilot — No external APIs. Local analysis only.",
      50,
      doc.page.height - 50,
      { align: "center", width: doc.page.width - 100 }
    );

    doc.end();
  });
}
